### ISSUE TITLE
A suggestion to make `render_readme` less frustrating

### ISSUE THREAD

**Issue by bahadzie** [epiverse-trace/packagetemplate#132]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

As a developer I should have the option to render `README.Rmd` locally and push both `README.Rmd` and `README.md` in my commit. In such a case I think the `Commit files` step in the `render_readme` workflow should not run to create an additional commit.

> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.

I propose adjusting the flow to compare the output of the `Compile the readme` step with `README.md` and only commit the updated `README.md` if it's different.

> **Additional context**
> Add any other context or screenshots about the feature request here.

This is a small change but it will remove the unnecessary mental friction I get trying to push a second commit after pushing one that updated `README.Rmd` and it failing because an extra commit was added at origin that I now have to pull in before I can push mine.

**Comment by Bisaloo** [comment]
> I propose adjusting the flow to compare the output of the Compile the readme step with README.md and only commit the updated README.md if it's different.

This should already be the case. Could you link to a PR where it's not behaving this way please?

**Comment by bahadzie** [comment]
> This should already be the case. Could you link to a PR where it's not behaving this way please?

- https://github.com/epiverse-trace/numberize/pull/3/commits/7169af629984f18b1cb3838feaa4f6c60f6b69c9
- https://github.com/epiverse-trace/numberize/pull/8/commits/10288faa7419f7062cef8fb57a3dd09f67a71e5e

I don't see anything in the Github Action that is optionally committing these files. It appears that it always runs the steps in the code snippet below, taken directly from the `render-readme.yml` file.
```
      - name: Compile the readme
        run: |
          writeLines(
            knitr::knit_expand(
              "README.Rmd",
              packagename = read.dcf("DESCRIPTION", "Package"),
              gh_repo = Sys.getenv("GITHUB_REPOSITORY")
            ),
            "README_expanded.Rmd"
          )
          rmarkdown::render(
            "README_expanded.Rmd",
            output_file = "README.md",
            output_dir = "."
          )
        shell: Rscript {0}

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # Also add README figures if they exist
          if [ -d man/figures ]
          then
            git add man/figures/
          fi
          git diff-index --quiet HEAD || git commit -m "Automatic readme update"
          git pull --rebase origin ${{ github.ref.name }}
          git push origin || echo "No changes to push"
```

**Comment by Bisaloo** [comment]
> git diff-index --quiet HEAD || git commit -m "Automatic readme update"

This step is saying: check if there are no changes to commit. If not, commit.

> https://github.com/epiverse-trace/numberize/commit/7169af629984f18b1cb3838feaa4f6c60f6b69c9
    https://github.com/epiverse-trace/numberize/commit/10288faa7419f7062cef8fb57a3dd09f67a71e5e

It's kind of behaving as desired here. The automatically rendered README differs from the previous version so it's rendered.

We could potentially tell it to ignore whitespace changes but it may then be annoying when someone wants a whitespace change to be rendered.

How did you render the README locally? I would expect it to match exactly what the GitHub Actions workflow is creating.

**Comment by bahadzie** [comment]
I'm using a slightly modified version of the `Compile the readme` step in the Github Action to account for the `GITHUB_REPOSITORY` environment variable when run locally.

```R
render_readme <- function() {
  writeLines(
    knitr::knit_expand(
      "README.Rmd",
      packagename = read.dcf("DESCRIPTION", "Package"),
      # modified to allow it to be run locally
      gh_repo = ifelse(
        Sys.getenv("GITHUB_REPOSITORY") == "",
        gsub( # this makes it run locally
          "https://github.com/", "",
          read.dcf(
            "DESCRIPTION", "URL"
          )[1],
          fixed = TRUE
        ),
        Sys.getenv("GITHUB_REPOSITORY")
      )
    ),
    "README_expanded.Rmd"
  )
  rmarkdown::render(
    "README_expanded.Rmd",
    output_file = "README.md",
    output_dir = "."
  )
  unlink("README_expanded.Rmd")
  unlink("README.html")
}
```

**Comment by Bisaloo** [comment]
This kind of diff in line breaks will happen when you switch to RStudio visual markdown editor. Is it possible that is what happened here?

In all cases, your initial requested feature in this issue is already implemented so this issue should likely be closed.
