### ISSUE TITLE
Move instructions to wiki

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/packagetemplate#15]
The current README structure is a bit awkward because it mixes a template for the README, as well as instructions on how to use this template & how to create a new R package from the command line.

It would be clearer if the README just included a skeleton of the information we want to include in the READMEs of all Epiverse-TRACE packages. I'd recommend we move the "meta" instructions to the Wiki of this repo.

@pratikunterwegs, since you created the command-line instructions, how would you feel about moving them to the wiki?

**Comment by pratikunterwegs** [comment]
Yes sure - I'll move them manually to the wiki, but delete them as a commit from the README.

**Comment by Bisaloo** [comment]
Should we also update the instructions to create the repo from the template in the command lines instructions? The current command line instructions will miss the part about lintr for example.

We could recommend 

```sh
gh repo create mypackage --template epiverse-trace/packagetemplate
```

what do you think?
