### ISSUE TITLE
Improve resource usage of GitHub Actions

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/packagetemplate#25]
As mentioned by @TimTaylor on the internal slack workspace, and as discussed on the [[R-pkg-devel] mailing list](https://stat.ethz.ch/pipermail/r-package-devel/2023q1/008924.html), we should be conscious of our resource usage when usage GitHub Actions. Especially, since [we collectively agreed in our values that we aim at being environmentally conscious](https://data.org/news/epiverse-trace-a-values-based-approach-to-open-source-ecosystems/).

Here are couple of ideas:

- from @TimTaylor: only run `R CMD check` when a change to the package has been made. In particular, we don't expect changes to the README, `_pkgdown.yml`, other GHA workflow files, etc. to change the output of `R CMD check`
- use a [fail-fast strategy for matrix workflow](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast). For example, if `R CMD check` fails on macOS, we could immediately stop `R CMD check` on all other platforms since we have already noticed an error to fix and there's no need to confirm it on other platforms. A potential downside here is that it makes platform-specific errors more difficult to identify and to diagnose.
- stop workflows triggered by previous commits if a new commit has been pushed. The idea is that the result of `R CMD check` or `lintr` or older commits will lead to an outdated and useless result. This is already implemented in the `pkgdown.yml` workflow and could be replicated in other workflows.

https://github.com/epiverse-trace/packagetemplate/blob/188938892a521c660f022d99c40807a580f08bd1/.github/workflows/pkgdown.yaml#L18-L19

Comments on these ideas and further suggestions are very welcome!

**Comment by TimTaylor** [comment]
All three sound good but understand the concern on the second one (you also occasionally get non-package related on particular builds).
