### ISSUE TITLE
Configure the CI workflows for merge queues

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/packagetemplate#72]
Now that merge queues are available, it might be worth considering [adding a merge queue to the list of triggers](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues) for the template CI workflows.

**Comment by Bisaloo** [comment]
Yes, I think it's a good change. It's invisible to anyone who is not using merge queues but leaves it as an option for anyone who might want to use them.

Can you submit a PR for this please? And for the [`lint-changed-files` workflow](https://github.com/epiverse-trace/.github/blob/main/workflows/lint-changed-files.yaml) as well please?

**Comment by jamesmbaazam** [comment]
> It's invisible to anyone who is not using merge queues but leaves it as an option for anyone who might want to use them.

Yes, exactly.

Thanks. I will submit a PR asap.
