### ISSUE TITLE
Add Github Actions to keep the following files in sync: `CITATION.cff`, CITATION, and DESCRIPTION

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/packagetemplate#73]
Using this [conversation on {bpmodels} about CITATION.cff files](https://github.com/epiverse-trace/bpmodels/pull/79#issuecomment-1632900692) as inspiration, I would like ask that we:
- Consider adding `CITATION.cff` to our packages to ease the process of citing our packages,
- Add a GHA configuration to packagetemplate for prospective use to sync the three files listed in the title above. 

The following [article](https://www.r-bloggers.com/2021/11/cffr-create-a-citation-cff-file-for-your-r-package/) provides more context on the benefit of using `.cff` files.

Tagging @joshwlambert as he raised this.

**Comment by Bisaloo** [comment]
This is to be addressed as part of #29 & #31
